# Generated by Django 2.0.1 on 2018-01-07 10:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='changeValue',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 1, 7, 10, 51, 21, 67555)),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 1, 7, 10, 51, 21, 62219)),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity_value',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='team',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 1, 7, 10, 51, 21, 63639)),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 1, 7, 10, 51, 21, 66032)),
        ),
    ]
