# Generated by Django 2.0.1 on 2018-02-12 05:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20180107_1139'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suppliers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(max_length=100)),
                ('due_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('team', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime(2018, 2, 12, 5, 5, 46, 873789))),
            ],
        ),
        migrations.AlterField(
            model_name='notifications',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 2, 12, 5, 5, 46, 871678)),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 2, 12, 5, 5, 46, 865917)),
        ),
        migrations.AlterField(
            model_name='team',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 2, 12, 5, 5, 46, 867521)),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 2, 12, 5, 5, 46, 870085)),
        ),
    ]
