# Generated by Django 2.0.1 on 2018-02-14 15:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20180212_0505'),
    ]

    operations = [
        migrations.AddField(
            model_name='suppliers',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 2, 14, 15, 2, 54, 274026)),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 2, 14, 15, 2, 54, 268101)),
        ),
        migrations.AlterField(
            model_name='suppliers',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 2, 14, 15, 2, 54, 276153)),
        ),
        migrations.AlterField(
            model_name='team',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 2, 14, 15, 2, 54, 269679)),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 2, 14, 15, 2, 54, 272326)),
        ),
    ]
